- config/file_storage.php
and remove configuration for ContentImages which is unnecessary because it is used by CKeditor only which the size can be manipulated by the editor.
> Optional config (task #1472)

- src/Controller/CategoriesController.php
- src/Template/Categories/add.ctp
- src/Template/Categories/edit.ctp
- src/Template/Categories/index.ctp
- src/Template/Categories/view.ctp
> Fix categories layout (task #1662)

- src/Controller/ArticlesController.php
- src/Template/Articles/edit.ctp
- src/Template/Element/featured-image-preview.ctp
>  	Implemented soft featured image delete (task #2151)

- src/Controller/ArticlesController.php
- src/Model/Table/ArticlesTable.php
- src/Template/Articles/index.ctp
- webroot/css/articles.css
> Search articles functionallity (task #2160)

- src/Model/Table/CategoriesTable.php
- src/Template/Articles/index.ctp
> Fixed displaying articles in category template, added publish indicator in articles index (task #2234)

- .gitignore
- .travis.yml
- composer.json
- phpunit.xml.dist
- src/Controller/ArticlesController.php
- src/Controller/CategoriesController.php
- src/Model/Table/ArticleFeaturedImagesTable.php
- src/Model/Table/ContentImagesTable.php
- tests/TestCase/Model/Table/CategoriesTableTest.php
* Merged with [cakephp-plugin-template v1.0.0](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v1.0.0)
* Added CodeSniffer to development requirements
* Fixed some coding style issues
> Cakephp plugin template

- config/routes.php
- src/Controller/ArticlesController.php
- src/Controller/CategoriesController.php
- src/Controller/UploadTrait.php
- src/Model/Table/ArticlesTable.php
- src/Model/Table/CategoriesTable.php
- Controller actions are all sent to display which is wrong.
- Created a task on Redmine and will look at it later.
> Revert "Routes improvement (task #2272)"

- config/Migrations/20170224142429_DropArticlesCategories.php
- config/Migrations/20170224142755_AddCategoryIdToArticles.php
- src/Controller/ArticlesController.php
- src/Model/Entity/Article.php
- src/Model/Table/ArticlesTable.php
- src/Model/Table/CategoriesTable.php
- src/Template/Articles/add.ctp
- src/Template/Articles/edit.ctp
- src/Template/Articles/index.ctp
- src/Template/Articles/view.ctp
Changed Articles and Categories association from `many-to-many` to `one-to-many`. Now an article can belong only to one category, but a category can have many articles.
> Tables associations (task #3387)

- config/Migrations/20170224120321_CreateSites.php
- config/Migrations/20170224155035_AddSiteIdToCategories.php
- config/Migrations/20170224155506_AlterSlugColumnInCategories.php
- src/Controller/CategoriesController.php
- src/Controller/SitesController.php
- src/Controller/UploadTrait.php
- src/Model/Entity/Site.php
- src/Model/Table/ArticlesTable.php
- src/Model/Table/CategoriesTable.php
- src/Model/Table/SitesTable.php
- src/Template/Articles/add.ctp
- src/Template/Articles/edit.ctp
- src/Template/Articles/index.ctp
- src/Template/Categories/add.ctp
- src/Template/Categories/edit.ctp
- src/Template/Categories/index.ctp
- src/Template/Categories/view.ctp
- src/Template/Sites/add.ctp
- src/Template/Sites/edit.ctp
- src/Template/Sites/index.ctp
- src/Template/Sites/view.ctp
- tests/Fixture/SitesFixture.php
- tests/TestCase/Controller/SitesControllerTest.php
- tests/TestCase/Model/Table/SitesTableTest.php
This is an initial implementation of cms Sites module. Needs more work to get it to stable version.
> Sites module (task #3387)

- composer.json
- config/Migrations/20170313134723_AddTrashedToArticles.php
- config/Migrations/20170314103527_AddSiteIdToArticles.php
- config/Migrations/20170314133200_AlterCreatedByInArticles.php
- config/Migrations/20170314133205_AlterModifiedByInArticles.php
- config/routes.php
- src/Controller/ArticlesController.php
- src/Controller/CategoriesController.php
- src/Controller/SitesController.php
- src/Model/Table/ArticlesTable.php
- src/Model/Table/BaseTable.php
- src/Model/Table/CategoriesTable.php
- src/Model/Table/SitesTable.php
- src/Template/Articles/index.ctp
- src/Template/Articles/view.ctp
- src/Template/Categories/add.ctp
- src/Template/Categories/edit.ctp
- src/Template/Categories/index.ctp
- src/Template/Sites/index.ctp
- src/Template/Sites/view.ctp
- Routes have been modified to require site `slug` or `id`.
- CRUD actions now require `site_id` to be provided.
- Trashed behavior added to Articles table.
> Articles refactoring (task #3387)

- src/Template/Element/Articles/blocks.ctp
- src/Template/Element/Articles/list.ctp
- Split articles list View into more blocks.
- Fixed issue with action buttons attached to the wrong element.
> Articles list View blocks (task #3905)

- config/elfinder.php
- config/tinymce.php
- src/Template/Element/Articles/single.ctp
- src/Template/Element/Types/Gallery/single.ctp
- src/View/Shortcode.php
- webroot/js/tinymce.init.js
- Added lightbox functionality in image galleries (requires [PR](https://github.com/QoboLtd/cakephp-utils/pull/41) merge and release).
- Added insert gallery button and custom functionality:
> Multiple images support (task #3945)

- src/Controller/AppController.php
- src/Model/Table/ArticlesTable.php
Added CMS search functionality.
> CMS articles search (task #3912)

- src/Template/Element/tinymce.ctp
Load `elFinder​` javascript code using cake's script block.
> Fix for galleries navigation (task #4204)

- config/cms.php
- src/Template/Articles/type.ctp
- src/Template/Articles/view.ctp
- src/Template/Categories/view.ctp
- src/Template/Element/sidebar.ctp
- src/Template/Sites/view.ctp
Conditionally display sidebar sections based on configuration parameters.
Example config:
```php
// /config/cms.php
return [
'CMS' => [
'Sidebar' => [
'display' => [
'categories' => true,
'types' => false // hide types section from sidebar
]
],
...
]
```
> Sidebar sections (task #4266)

- src/Model/Table/CategoriesTable.php
- src/Model/Table/SitesTable.php
Display only categories and nested level categories that have at least one article under their sub level tree.
> side menu categories visibility (task #4025)

- src/Controller/ArticlesController.php
- src/Controller/CategoriesController.php
- src/Controller/SitesController.php
- src/Model/Table/CategoriesTable.php
- src/Model/Table/SitesTable.php
- src/Template/Element/Categories/sidebar.ctp
- src/Template/Element/sidebar.ctp
re implement logic for marking categories that have articles with query,
also added extra variable for storing the filtered categories in actions needed
> side menu categories retrieve improvements (task #4025)

- src/Model/Table/ArticleFeaturedImagesTable.php
Fixing issues identified by PHPStan
> Minor docblock fix

- src/Model/Table/ArticlesTable.php
- src/View/Shortcode.php
- tests/TestCase/Model/Table/ArticlesTableTest.php
Added caching on CMS shortcodes.
> Shortcodes caching (task #5023)

- src/Template/Sites/view.ctp
> Replaced indents. (task #5501)

- src/View/Shortcode.php
- tests/TestCase/View/ShortcodeTest.php
After closing #152 due to a little bug, I have fixed it and now created a new PR.
You can find the discussion about this feature in #151.
> Get content from shortcode

- config/Migrations/20160316112622_FixArticlesCreatedModifiedFields.php
- config/Migrations/20160321144838_UpdateArticlesFields.php
- config/Migrations/20180516130445_RenameArticlesTable.php
- config/Migrations/20180516130714_RenameCategoriesTable.php
- config/Migrations/20180516131033_RenameSitesTable.php
We adjust the migrations so that work with CakePHP v3.8
> Fix migrations for CakePHP v3.8

- src/Controller/SitesController.php
- src/Template/Sites/view.ctp
Enables pagination for v9.2.0-patch2
> Enable pagination
